import React from 'react';

export const PublishGuide: React.FC<{onBack: () => void}> = ({onBack}) => {
  return (
    <div className="h-full bg-slate-50 pb-24 animate-fade-in overflow-y-auto">
      <header className="px-6 pt-8 pb-4 sticky top-0 bg-slate-50 z-10 flex items-center gap-4">
        <button onClick={onBack} className="p-2 -ml-2 text-slate-600 hover:bg-slate-200 rounded-full">
          <span className="material-icons-round">arrow_back</span>
        </button>
        <h1 className="text-xl font-bold text-slate-900">Publishing Guide</h1>
      </header>

      <div className="px-6 space-y-6 text-slate-700">
        <section className="bg-white p-6 rounded-xl shadow-sm border border-slate-200">
          <h2 className="text-lg font-bold text-brand-600 mb-3">Option 1: The Easy Way (No Store)</h2>
          <p className="text-sm leading-relaxed mb-4">
            You don't need the App Store to use this on your phone!
          </p>
          <ol className="list-decimal pl-5 text-sm space-y-3">
            <li>
              <strong>Deploy code:</strong> Upload these files to a host like <a href="https://vercel.com" target="_blank" className="text-blue-500 underline">Vercel</a> or <a href="https://netlify.com" target="_blank" className="text-blue-500 underline">Netlify</a> (It's free).
            </li>
            <li>
              <strong>IMPORTANT - Set API Key:</strong> In your Vercel/Netlify dashboard, go to <strong>Settings &rarr; Environment Variables</strong>. Add a new variable:
              <ul className="list-disc pl-4 mt-1 text-slate-500">
                <li>Name: <code>API_KEY</code></li>
                <li>Value: <code>Your_Google_Gemini_API_Key</code></li>
              </ul>
            </li>
            <li>
              <strong>Open on Phone:</strong> Visit your new website URL on your mobile browser.
            </li>
            <li>
              <strong>Install:</strong>
              <ul className="list-disc pl-4 mt-1 text-slate-500">
                <li>Android: Tap 3 dots &rarr; <strong>Install App</strong></li>
                <li>iOS: Tap Share &rarr; <strong>Add to Home Screen</strong></li>
              </ul>
            </li>
          </ol>
        </section>

        <section className="bg-white p-6 rounded-xl shadow-sm border border-slate-200">
          <h2 className="text-lg font-bold text-brand-600 mb-3">Option 2: Get an APK file</h2>
          <p className="text-sm mb-3">If you really want a physical <code>.apk</code> file to share:</p>
          <ol className="list-decimal pl-5 text-sm space-y-2">
            <li>Complete "Step 1" above (Deploy the code).</li>
            <li>Copy your new website URL.</li>
            <li>Go to <a href="https://www.pwabuilder.com" target="_blank" className="text-blue-500 underline font-bold">PWABuilder.com</a>.</li>
            <li>Paste your URL and click <strong>Start</strong>.</li>
            <li>Click <strong>Package for Store</strong> (Android).</li>
            <li>Download the generated <strong>APK</strong> file.</li>
          </ol>
        </section>

        <section className="bg-white p-6 rounded-xl shadow-sm border border-slate-200">
          <h2 className="text-lg font-bold text-brand-600 mb-3">Option 3: Play Store</h2>
          <p className="text-sm">
            Follow "Option 2", but instead of just sharing the APK, you take the <code>.aab</code> file (also generated by PWABuilder) and upload it to the Google Play Console. Note that Google charges a $25 fee for a developer account.
          </p>
        </section>

        <div className="mt-8 pt-6 pb-2 text-center">
            <p className="text-xs text-slate-400 font-semibold tracking-wide uppercase">Made by Zoraiz Al Raz 2025</p>
        </div>
      </div>
    </div>
  );
};